### ISSUE TITLE
Currency displayed

### ISSUE THREAD

**Issue by bluuurgh** [edasque/Stock-quotes-Widget#1]
Great widget but it shows all values in USD even if I ask for stocks on EuroNext.

Example, ASML.AS is now at e130.40 but in the widget I see $130.40. 
Same for EURGBP=X, the value of the British pound in euro.

Not really an issue as I know the currency the stocks are in but it would be nice to see them correctly.

**Comment by edasque** [comment]
Good point. I have a brand new version of the widget, with sparklines so I'll look into the currency soon.

**Comment by edasque** [comment]
Unfortunately because the Yahoo API got deprecated, I had to move to the RH API which AFAIK doesn't support non US stock
